### ISSUE TITLE
Launcher does not work offline

### ISSUE THREAD

**Issue by matthme** [holochain/launcher-tauri#78]
**Describe the bug**
The launcher does not work well offline. App UI's cannot be opened.

**To Reproduce**
1. Start the launcher without internet connection
2. Apps are paused and cannot be opened

**Expected behavior**
I think Holochain should have the aspiration to work offline.

**Logs**
-

**Screenshots**
-

**Desktop (please complete the following information):**
-

**Additional context**
-

**Comment by matthme** [comment]
Checklist of things to improve:
- [ ] Reasonable UX to "restart/refresh" apps when back online. Currently each app needs to be started separately or the launcher needs to be restarted as a whole
- [ ] App UI's can be opened when offline

**Comment by Connoropolous** [comment]
we have the same issue with Acorn I believe. Seriously want to fix

**Comment by matthme** [comment]
I haven't look into it in detail yet but it might actually be that the AdminWebsocket as it currently works does not allow you to get a hApp running without internet connection because the bootstrapping process fails and the hApp consequently has status paused. I'm just guessing that because I saw a bootstrap error in the launcher logs when being offline but since you say you have the same problem in Acorn it might indeed be an AdminWebsocket issue.

**Comment by Connoropolous** [comment]
your assessment is quite similar to mine, which I haven't highly investigated, but had glimpses of a similar root cause

**Comment by guillemcordoba** [comment]
Yeah I think that's the issue but it's not about the AdminWebsocket itself. When the conductor starts, it tries to boot up all the cells, and in that process goes to the bootstrapping service to get the nodes. If it can't reach the bootstrapping service which is hosted in cloudflare, it pauses the app. This needs to change in holochain core I think.

**Comment by Connoropolous** [comment]
I've pushed the issue through to holochain upstream, and I see Michael has seen the above, confirming. 
I've also just linked the corresponding Acorn issue as well

**Comment by matthme** [comment]
More details about the issue: https://github.com/holochain/holochain/issues/1580#issuecomment-1377471698

**Comment by matthme** [comment]
Conflated status "Running" and "Paused" into just "Running" with cbb36fd6a89ea68161c30feb3d5d8707a54107aa. Still not ideal behavior especially when it comes to disabling and enabling cells while being offline. But when the Launcher is being opened offline and the app is "Paused" according to what the js-client returns, it still seems to be fully functional locally, i.e. stuff can be committed to the source chain and when getting back online, gossip starts again and other peers receive the data commited while being offline (tested).
